apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  generateName: hello-goodbye-run-
  namespace: tekton-demo
spec:
  pipelineRef:
    name: hello-goodbye
status: {}
