apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
  namespace: tekton-demo
spec:
  steps:
    - name: hello
      image: alpine
      command:
        - echo
      args:
        - "Hello World!"
